# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://help.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: github-actions # See documentation for possible values
    directory: "/" # Location of package manifests
    rebase-strategy: "auto"
    schedule:
      interval: weekly
      time: "02:00"
    open-pull-requests-limit: 10
  - package-ecosystem: "npm" # See documentation for possible values
    directory: "/" # Location of package manifests
    rebase-strategy: "auto"
    schedule:
      interval: "weekly"
      time: "02:00"
    open-pull-requests-limit: 10
    # Group updates so related packages (e.g. all @nestjs/*) are proposed in a single PR.
    # This helps keep versions in sync when a scoped library publishes coordinated releases.
    groups:
      nestjs:
        patterns:
          - "@nestjs/*"
      commit:
        patterns:
          - "@commitlint/*"
          - "lint-staged"
          - "husky"
      webpack:
        patterns:
          - "webpack"
          - "webpack-*"
          - "run-script-webpack-plugin"
      typescript:
        patterns:
          - "typescript"
          - "@types/*"
          - "tslib"
          - "ts-node"
      discord:
        patterns:
          - "discord.js"
          - "@discordjs/*"
          - "discord-api-types"
      necord:
        patterns:
          - "necord"
          - "@necord/*"
      otel:
        patterns:
          - "@opentelemetry/*"
          - "opentelemetry-*"
          - "@sesamecare-oss/opentelemetry-node-metrics"
          - "@prisma/instrumentation"

