project_id_env: CROWDIN_PROJECT_ID
api_token_env: CROWDIN_PERSONAL_TOKEN
base_path: .
base_url: "https://api.crowdin.com/"
preserve_hierarchy: 1
files:
  - source: Packages/Client/src/common/Languages/i18n/en-US/
    translation: Packages/Client/src/common/Languages/i18n/%locale%/
  - source: Packages/Client/src/common/Languages/i18n/pt-BR/
    translation: Packages/Client/src/common/Languages/i18n/%locale%/
