"project_id_env": "CROWDIN_PROJECT_ID"
"api_token_env": "CROWDIN_PERSONAL_TOKEN"
"base_path": "."
"base_url": "https://crowdin.com/project/n-d-b"

"preserve_hierarchy": true

files:
  [
    {
      "source": "Packages/Client/Src/Utils/Languages/i18next/en-US/",
      "translation": "Packages/Client/Src/Utils/Languages/i18next/%locale%/"
    }
  ]
