version: "3.8"

services:
  ndbase:
    build: .docker/Postgres/
    container_name: ndbase
    restart: always
    tty: true
    ports:
      - "5432:5432"
    volumes:
      - .docker/database/postgres/development:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
  lavalink:
    build: Packages/Lavalink
    container_name: lavalink
    restart: unless-stopped
    environment:
      - _JAVA_OPTIONS=-Xmx6G
      - SERVER_PORT=2333
      - LAVALINK_SERVER_PASSWORD=${LAVALINK_SERVER_PASSWORD}
    expose:
      - 2333
    ports:
      - "2333:2333"
  redis:
    build: .docker/Redis
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
