include:
  - path: ./Database/docker-compose.yml
    env_file: .env.development
  - path: ./Lavalink/docker-compose.yml
    env_file: .env.development

services:
  bot:
    container_name: ndbot
    build: .
    restart: always
    tty: true
    env_file: .env.development
    working_dir: /usr/app
    networks:
      - ndnetwork

networks:
  ndnetwork:
    driver: bridge
