include:
  - path: ./Database/docker-compose.yml
    env_file: .env
  - path: ./Lavalink/docker-compose.yml
    env_file: .env

services:
  bot:
    container_name: ndbot
    build: .
    restart: always
    tty: true
    env_file: .env
    working_dir: /usr/app
    networks:
      - ndnetwork

networks:
  ndnetwork:
    driver: bridge
