version: "3.8"

services:
  bot:
    container_name: ndbot
    build: .
    restart: always
    tty: true
    volumes:
      - .:/usr/app
      - /usr/app/node_modules
    working_dir: /usr/app
    command: >
      make start
    networks:
      - ndnetwork

networks:
  ndnetwork:
