include:
  - path: ./Database/docker-compose.yml
    env_file: .env
  - path : ./Lavalink/docker-compose.yml
    env_file: .env

services:
  bot:
    container_name: ndbot
    build: .
    restart: always
    tty: true
    env_file: .env
    volumes:
      - .:/usr/app
      - /usr/app/node_modules
    working_dir: /usr/app
    command: >
      make start-dev
    networks:
      - ndnetwork

networks:
  ndnetwork:
    driver: bridge
