version: "3"

services:
  ndbase:
    build: .docker/Postgres/
    container_name: ndbase
    restart: always
    tty: true
    ports:
      - "5432:5432"
    volumes:
      - .docker/database/postgres/development:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
  redis_ndbase:
    build: .docker/Redis
    container_name: redis_ndbase
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - .docker/database/redis/development:/usr/local/etc/redis
