global:
  scrape_interval:     15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'otel-collector'
    scrape_interval: 2s
    static_configs:
    - targets: ['ndopentelemetry-collector:8889']

storage:
  tsdb:
    out_of_order_time_window: 30m
