export enum ClusterStatus {
  REGISTERED = "REGISTERED",
  LOGGING_IN = "LOGGING_IN",
  READY = "READY",
  PARTIALLY_ONLINE = "PARTIALLY_ONLINE",
  ONLINE = "ONLINE",
  OFFLINE = "OFFLINE",
  ERROR = "ERROR",
}
