-- AlterTable
ALTER TABLE "GuildChannels" ALTER COLUMN "Logs" SET DATA TYPE TEXT;

-- AlterTable
ALTER TABLE "GuildReactionRoles" ALTER COLUMN "Channel" SET DATA TYPE TEXT,
ALTER COLUMN "Role" SET DATA TYPE TEXT;

-- AlterTable
ALTER TABLE "GuildRoles" ALTER COLUMN "Default" SET DATA TYPE TEXT,
ALTER COLUMN "Muted" SET DATA TYPE TEXT;
