name: Generate Coverage Commit

on:
  push:
    branches:
      - master
    paths:
      - "Packages/**/*.ts"

jobs:
  generate-coverage-commit:
    strategy:
      matrix:
        node-version: [20.6.1]

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: yarn install
        env:
          # Disable Husky in CI
          # https://typicode.github.io/husky/how-to.html#skipping-git-hooks
          HUSKY: "0"

      - name: Generate coverage report
        run: |
          yarn test --coverage
          mkdir -p ../coverage/client
          mv index.html ../coverage
          mv Packages/Client/test/coverage/lcov-report ../coverage/client
          mv Packages/Client/test/coverage/lcov.info ../coverage/client

      - name: Create and switch to Coverage-Report branch
        run: |
          git checkout -b Coverage-Report
          git rm -rf .
          git clean -f -d

      - name: Move coverage folder to Coverage-Report branch
        run: |
          mv ../coverage/client .
          mv ../coverage/index.html .

      - name: Commit changes
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add .
          git commit -m "feat: Add test coverage report"
        
      - name: Pull changes from remote
        run: git pull origin Coverage-Report

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: Coverage-Report
      
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONARCLOUD_TOKEN }}
