name: Run Tests

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  run-tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.6.1]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4

    - name: Disable Husky during CI
      run: yarn ci-setup

    - name: Install dependencies
      run: yarn install

    - name: Navigate to Client package
      run: cd Packages/Client

    - name: Run tests
      run: yarn test
