name: Run Tests

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  run-tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.6.1]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4

    - name: Install dependencies
      run: yarn install --immutable
      env:
        # Disable Husky in CI
        # https://typicode.github.io/husky/how-to.html#skipping-git-hooks
        HUSKY: "0"

    - name: Run tests
      run: yarn test
      env:
        RUST_BACKTRACE: "1"
